export const userList = [
  {
    id: 'user1',
    password: 'password1',
    name: 'John mina',
    age: 28,
    email: 'john.smith@example.com',
    profileImage: 'https://randomuser.me/api/portraits/men/28.jpg',
    jobs: '소프트웨어 엔지니어',
  },
  {
    id: 'user2',
    password: 'password2',
    name: 'Emily Johnson',
    age: 32,
    profileImage: 'https://randomuser.me/api/portraits/women/32.jpg',
    email: 'emily.johnson@example.com',
    jobs: '마케팅 매니저',
  },
  {
    id: 'user3',
    password: 'password3',
    name: 'David Lee',
    age: 45,
    profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
    email: 'david.lee@example.com',
    jobs: '금융 컨설턴트',
  },
  {
    id: 'user4',
    password: 'password4',
    name: 'Sarah Wilson',
    age: 35,
    profileImage: 'https://randomuser.me/api/portraits/women/35.jpg',
    email: 'sarah.wilson@example.com',
    jobs: '디자이너',
  },
  {
    id: 'user5',
    password: 'password5',
    name: 'Michael Davis',
    age: 31,
    profileImage: 'https://randomuser.me/api/portraits/men/31.jpg',
    email: 'michael.davis@example.com',
    jobs: '영화 감독',
  },
  {
    id: 'user6',
    password: 'password6',
    name: 'Jessica Anderson',
    age: 27,
    profileImage: 'https://randomuser.me/api/portraits/women/27.jpg',
    email: 'jessica.anderson@example.com',
    jobs: '작가',
  },
  {
    id: 'user7',
    password: 'password7',
    name: 'Andrew Thompson',
    age: 39,
    profileImage: 'https://randomuser.me/api/portraits/men/39.jpg',
    email: 'andrew.thompson@example.com',
    jobs: '비즈니스 개발자',
  },
  {
    id: 'user8',
    password: 'password8',
    name: 'Olivia Martinez',
    age: 29,
    profileImage: 'https://randomuser.me/api/portraits/women/29.jpg',
    email: 'olivia.martinez@example.com',
    jobs: '의사',
  },
  {
    id: 'user9',
    password: 'password9',
    name: 'Ethan Harris',
    age: 33,
    profileImage: 'https://randomuser.me/api/portraits/men/33.jpg',
    email: 'ethan.harris@example.com',
    jobs: '교육자',
  },
  {
    id: 'user10',
    password: 'password10',
    name: 'Sophia Clark',
    age: 26,
    profileImage: 'https://randomuser.me/api/portraits/women/26.jpg',
    email: 'sophia.clark@example.com',
    jobs: '엔터테인먼트 기자',
  },
];
